services:
  - type: web
    name: procure-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py create_test_users || true && python manage.py collectstatic --no-input
    startCommand: gunicorn config.wsgi:application

  - type: web
    name: procure-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html